#!/bin/bash

#PBS -S /bin/bash
#PBS -l pmem=2000mb
#PBS -l procs=1
#PBS -l walltime=24:00:00
#PBS -m bea
#PBS -M erosolow@ualberta.ca
#PBS -l epilogue=/home/eros/bin/epilogue.sh

module load intel/14.0.2

export EHOME=/home/eros/
export PPDIR=$EHOME/simscript/postproc/
export PYTHONPATH=$PYTHONPATH+':'+$PPDIR
source $EHOME/yt-x86_64/bin/activate
cd $PBS_O_WORKDIR
echo "Current working directory is `pwd`"

